# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
