# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_posicion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=60)),
                ('goles', models.IntegerField(default=0)),
            ],
        ),
    ]
