# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_goleador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.CharField(max_length=60)),
                ('amarillas', models.IntegerField(default=0)),
                ('rojas', models.IntegerField(default=0)),
                ('suspendido', models.IntegerField(default=0)),
            ],
        ),
    ]
