# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0004_tarjetas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarjetas',
            new_name='Tarjeta',
        ),
    ]
