# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=120)),
                ('nombre_abreviado', models.CharField(blank=True, max_length=120)),
                ('numero', models.IntegerField(default=0)),
                ('posicion', models.CharField(max_length=60)),
                ('fecha_nacimiemto', models.CharField(blank=True, max_length=120)),
                ('peso', models.CharField(blank=True, max_length=30)),
                ('altura', models.CharField(blank=True, max_length=60)),
                ('perfil', models.TextField()),
            ],
        ),
    ]
