# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuerpo_tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('puesto', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Directiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('puesto', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
