# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_cuerpo_tecnico_directiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuerpo_tecnico',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='directiva',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
