# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default=' ', max_length=30)),
                ('fecha', models.CharField(blank=True, max_length=30)),
                ('horario', models.CharField(blank=True, max_length=20)),
                ('estadio', models.CharField(blank=True, max_length=50)),
                ('nom_local', models.CharField(blank=True, max_length=100)),
                ('nom_visita', models.CharField(blank=True, max_length=100)),
                ('marcador', models.CharField(blank=True, default=' ', max_length=15)),
                ('estado', models.CharField(blank=True, default=' ', max_length=15)),
                ('num_tab', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
