# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_actual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Alineacion', max_length=30)),
                ('nombre_jugador_local', models.CharField(blank=True, default='-', max_length=50)),
                ('numero_jugador_local', models.CharField(blank=True, default='-', max_length=3, verbose_name='No.')),
                ('nombre_jugador_visita', models.CharField(blank=True, default='-', max_length=50)),
                ('numero_jugador_visita', models.CharField(blank=True, default='-', max_length=3, verbose_name='No.')),
            ],
        ),
        migrations.CreateModel(
            name='Cronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Cronica', max_length=200)),
                ('cronica', models.TextField(blank=True, default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Directo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='En directo', max_length=30)),
                ('minuto', models.CharField(blank=True, default=' ', max_length=3)),
                ('comentario', models.TextField(blank=True, default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Resultados', max_length=30)),
                ('equipo_uno', models.CharField(blank=True, default=' ', max_length=60)),
                ('resultado_uno', models.CharField(blank=True, default=' ', max_length=4)),
                ('equipo_dos', models.CharField(blank=True, default=' ', max_length=60)),
                ('resultado_dos', models.CharField(blank=True, default=' ', max_length=4)),
            ],
        ),
    ]
