# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_actual', '0002_alineacion_cronica_directo_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='logo_local',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jornada',
            name='logo_visita',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
