# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_actual', '0003_auto_20160717_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/static/photos'), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='jornada',
            name='logo_local',
            field=models.ImageField(blank=True, upload_to='Logo'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='logo_visita',
            field=models.ImageField(blank=True, upload_to='Logo'),
        ),
    ]
