# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_actual', '0004_auto_20160717_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AlterField(
            model_name='jornada',
            name='logo_local',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='logo_visita',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
